stages:
  - test
  - package

run-tests:
  stage: test
  image: python:3.9
  before_script:
    - pip install pdm pytest
    - VERSION=$(echo "$PYTHON_VERSION" | grep -Eo '[0-9]\.[0-9]+')
    - export PYTHONPATH="/usr/local/lib/python$VERSION/site-packages/pdm/pep582"
    - pdm install -G test
  script:
    - pytest -v

pip-package:
  stage: package
  rules:
    - if: "$CI_COMMIT_TAG"
  before_script:
    - pip install pdm twine
  script:
    - pdm build
    - >
      TWINE_PASSWORD=${PYPI_USER}
      TWINE_USERNAME=$(echo "$PYPI_PASS_BASE64" | base64 --decode)
      twine upload dist/*
