stages:
  - test
  - package

run-tests:
  stage: test
  image: python:3.9
  before_script:
    - pip install pdm pytest
    - VERSION=$(echo "$PYTHON_VERSION" | grep -Eo '[0-9]\.[0-9]+')
    - export PYTHONPATH="/usr/local/lib/python$VERSION/site-packages/pdm/pep582"
    - pdm install -G test
  script:
    - pytest --verbose

pip-package:
  stage: package
  image: python:3.9
  rules:
    - if: "$CI_COMMIT_TAG"
  before_script:
    - pip install pdm twine
  script:
    - pdm build
    - >
      twine upload
      -u "__token__"
      -p "$PYPI_API_TOKEN"
      dist/* --verbose --skip-existing
