stages:
  - test
  - deploy

workflow:
  rules:
    - if: >
        ($CI_COMMIT_REF_NAME == "main"
        || $CI_COMMIT_REF_NAME == "gh-pages")
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

run-tests:
  stage: test
  image: python:3.10
  before_script:
    - pip install pdm pytest
    - pdm config python.use_venv false
    - VERSION=$(echo "$PYTHON_VERSION" | grep -Eo '[0-9]\.[0-9]+')
    - export PYTHONPATH="/usr/local/lib/python$VERSION/site-packages/pdm/pep582"
    - pdm install -G test
  script:
    - pytest --verbose

pip-package:
  stage: deploy
  image: python:3.10
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - pip install pdm twine
    - pdm config python.use_venv false
  script:
    - pdm build
    - >
      twine upload
      -u "__token__"
      -p "$PYPI_API_TOKEN"
      dist/* --verbose --skip-existing

pages:
  stage: deploy
  image: python:3.10
  before_script:
    - pip install mkdocs-material
    - cd docs
  script:
    - mkdocs build --site-dir public
    - mv public ../public
  artifacts:
    paths:
      - public
