stages:
  - test
  - deploy

workflow:
  rules:
    - if: >
        ($CI_COMMIT_REF_NAME == "main"
        || $CI_COMMIT_REF_NAME == "gh-pages")
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

#run-tests:
#  stage: test
#  image: python:3.10
#  before_script:
#    - pip install pdm>=2.5.3 requests==2.29.0
#    - pdm install -G test
#  script:
#    - pdm run pytest --verbose

pip-package:
  stage: deploy
  image: python:3.10
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  before_script:
    - pip install pdm>=2.5.3 requests==2.29.0
  script:
    - pdm config repository.pypi.username "__token__"
    - pdm config repository.pypi.password "${PYPI_API_TOKEN}"
    - pdm publish

pages:
  stage: deploy
  image: python:3.10
  before_script:
    - pip install pdm>=2.5.3 requests==2.29.0
    - pdm install -G docs
  script:
    - cd docs
    - pdm run mkdocs build --site-dir public
    - mv public ../public
  artifacts:
    paths:
      - public
